apiVersion: claw.clawbernetes.io/v1
kind: ClawGateway
metadata:
  labels:
    app.kubernetes.io/name: hackaway-repo
    app.kubernetes.io/managed-by: kustomize
  name: clawgateway-sample
spec:
  # TODO(user): Add fields here
